---

 - hosts: all
   become: true
   pre_tasks:

   - name: install updates (Fedora)
     tags: always
     dnf:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Fedora"

   - name: install updates (Ubuntu)
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"

 - hosts: all
   become: true
   tasks:

   - name: add ssh key for Testuser
     tags: always
     authorized_key:
       user: testuser
       key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHU0/hMwyLJF+pemGu/llid9hSUkhWsrzbIXAwl1ImdS Ansible Demo Key"

 - hosts: web_servers
   become: true
   tasks:
   
   - name: install httpd package (Fedora)
     tags: apache,fedora,httpd
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "Fedora"

   - name: start httpd (Fedora)
     tags: apache,fedora,httpd
     service:
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "Fedora"

   - name: change e-mail address for admin
     tags: apache,fedora,httpd
     lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin somebody@somewhere.net
     when: ansible_distribution == "Fedora"
     register: httpd

   - name: restart httpd (Fedora)
     tags: apache,Fedora,httpd
     service:
       name: httpd
       state: restarted
     when: httpd.changed

   - name: install apache package (ubuntu)
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: copy default html file for site
     tags: apache,Apache2,httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

 - hosts: db_servers
   become: true
   tasks:

    - name: install mariadb server package (Fedora)
      tags: fedora,db,mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "Fedora"

    - name: install mariadb server
      tags: ubuntu,db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

 - hosts: file_servers
   become: true
   tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
